name: CI
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        
    - uses: actions/checkout@v3
    - name: Build app for release
      run: msbuild Driver\driver.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
