name: CI
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-2022
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
        
    - uses: actions/checkout@v3
    - name: Build app for release
      run: msbuild Driver\driver.sln -clp:Verbosity=m -t:clean,build -property:Platform=x64 -p:TargetVersion=Windows10 -verbosity:diag -p:InfVerif_AdditionalOptions="/msft /sw1205 /sw1324 /sw1420 /sw1421"  -p:SignToolWS=/fdws -p:DriverCFlagAddOn=/wd4996 -property:Configuration=Release
    - uses: actions/upload-artifact@v3
      with:
          path: efi1\efi1\Driver\x64\Release\driver.sys
